### ISSUE TITLE
Internal error on empty glabel

### ISSUE THREAD

**Issue by DaemonTsun** [matt-kempster/mips_to_c#196]
`mipsdisasm` spat out the following code:

```
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

glabel 
glabel _ftext
glabel main
/* 00013C 0890003C E0FFBD27 */  addiu $sp, $sp, -0x20
/* 000140 08900040 1C00BFAF */  sw    $ra, 0x1c($sp)
/* 000144 08900044 1800B2AF */  sw    $s2, 0x18($sp)
/* 000148 08900048 1400B1AF */  sw    $s1, 0x14($sp)
...
```

`mips_to_c` crashes on the empty glabel on line 4 with the error:

```
/*
Internal error:

Traceback (most recent call last):
  File "mips_to_c/src/main.py", line 72, in run
    mips_file = parse_file(f, options)
  File "mips_to_c/src/parse_file.py", line 444, in parse_file
    process_label(line.split()[1], glabel=True)
IndexError: list index out of range
*/
```

**Comment by simonlindholm** [comment]
Seems fine to ignore, done in cb9ecc07dad9993e64d8a141fc227a0f1a49cd8a. I'm surprised mipsdisasm gives you that though, and I'd expect it to give errors when assembling.
